server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: system-logs
          host: ${HOSTNAME}
          __path__: /var/log/*.log

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - docker: {}
      - labeldrop:
          - filename
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
      - source_labels: ["__meta_docker_container_labels"]
        regex: '.*com\.docker\.compose\.project=([^,]+).*'
        target_label: "compose_project"
      - source_labels: ["__meta_docker_container_labels"]
        regex: '.*com\.docker\.compose\.service=([^,]+).*'
        target_label: "compose_service"
      - source_labels: ["__meta_docker_container_networks"]
        target_label: "compose_networks"
